name: PHP Syntax Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Validar arquivos PHP
      run: find . -type f -name "*.php" -exec php -l {} \;

    - name: Validar composer.json (se existir)
      run: |
        if [ -f composer.json ]; then
          composer validate --strict
        else
          echo "composer.json não encontrado. Pulando validação."
        fi
